# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v3  
      - name: Restore the wallet
        env:
          CWALLET_SSO: ${{secrets.CWALLET_SSO}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          EWALLET_P12: ${{secrets.EWALLET_P12}}
          SQLNET_ORA: ${{secrets.SQLNET_ORA}}
          EWALLET_PEM: ${{secrets.EWALLET_PEM}}
          KEYSTORE_JKS: ${{secrets.KEYSTORE_JKS}}
          OJDBC_PROPERTIES: ${{secrets.OJDBC_PROPERTIES}}
          TNSNAMES_ORA: ${{secrets.TNSNAMES_ORA}}
          TRUSTSTORE_JKS: ${{secrets.TRUSTSTORE_JKS}}
        run: |
          pwd
          mkdir oracle
          echo "$CWALLET_SSO" | base64 -d > oracle/cwallet.sso
          echo "$EWALLET_P12" | base64 -d > oracle/ewallet.p12
          echo "$SQLNET_ORA" | base64 -d > oracle/sqlnet.ora
          echo "$EWALLET_PEM" | base64 -d > oracle/ewallet.pem
          echo "$KEYSTORE_JKS" | base64 -d > oracle/keystore.jks
          echo "$OJDBC_PROPERTIES" | base64 -d > oracle/ojdbc.properties
          echo "$TNSNAMES_ORA" | base64 -d > oracle/tnsnames.ora
          echo "$TRUSTSTORE_JKS" | base64 -d > oracle/truststore.jks
          ls oracle/

      - uses: liquibase-github-actions/update@v4.27.0
        with:
          changelogFile: "changelog.json"
          url: "jdbc:oracle:thin:@sqlpractice_low?TNS_ADMIN=/workspaces/codespaces-blank/oracle"
          username: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
